// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOLtITccaXMT6M3zYpFKr--8m5f3yuzSw',
    appId: '1:754321600370:web:05ee84c3296fdd3879b7eb',
    messagingSenderId: '754321600370',
    projectId: 'cloud-messaging-726d0',
    authDomain: 'cloud-messaging-726d0.firebaseapp.com',
    storageBucket: 'cloud-messaging-726d0.firebasestorage.app',
    measurementId: 'G-N5PSDR4N73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABqrRy1InX_Y5ZlkCceqGKKpjyjpdPEBI',
    appId: '1:754321600370:android:b96796a826af1c2579b7eb',
    messagingSenderId: '754321600370',
    projectId: 'cloud-messaging-726d0',
    storageBucket: 'cloud-messaging-726d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAluw9Ciw8CkfIG1adjA95BAF6Virio404',
    appId: '1:754321600370:ios:aa88c90a4c5c72ef79b7eb',
    messagingSenderId: '754321600370',
    projectId: 'cloud-messaging-726d0',
    storageBucket: 'cloud-messaging-726d0.firebasestorage.app',
    iosBundleId: 'com.example.madHw2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAluw9Ciw8CkfIG1adjA95BAF6Virio404',
    appId: '1:754321600370:ios:aa88c90a4c5c72ef79b7eb',
    messagingSenderId: '754321600370',
    projectId: 'cloud-messaging-726d0',
    storageBucket: 'cloud-messaging-726d0.firebasestorage.app',
    iosBundleId: 'com.example.madHw2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOLtITccaXMT6M3zYpFKr--8m5f3yuzSw',
    appId: '1:754321600370:web:ce8350d352dadc9579b7eb',
    messagingSenderId: '754321600370',
    projectId: 'cloud-messaging-726d0',
    authDomain: 'cloud-messaging-726d0.firebaseapp.com',
    storageBucket: 'cloud-messaging-726d0.firebasestorage.app',
    measurementId: 'G-KJ49X3H04P',
  );
}
